In [3]:
import numpy as np
import pandas as pd

# Exercise 1: (Score : 1) Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.

In [5]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)
print(arr1.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)


In [6]:
arr2=arr1.copy()

In [7]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
newarr2=arr2.reshape(2,1,5)
print(newarr2)
#print(arr2)

[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]]


# Exercise 2: (Score : 1) Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.

In [10]:
arr3=np.random.randint(1,20,size=20)
arr3

array([ 4, 10,  7, 16, 11,  6,  8, 16,  3, 15, 15, 10, 10, 16, 12, 14, 17,
       11,  4,  4])

In [11]:
print(arr3[5:16])

[ 6  8 16  3 15 15 10 10 16 12 14]


# Exercise 3: (Score : 2) Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.

In [13]:
data1={'apples': 3, 'bananas': 2, 'oranges': 1}
df=pd.Series(data1)
print(df)

apples     3
bananas    2
oranges    1
dtype: int64


In [14]:
df["pears"]=4
print(df)

apples     3
bananas    2
oranges    1
pears      4
dtype: int64


# Exercise 4: (Score : 2) Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data. 

In [16]:
data2={"Name":['Alice', 'Bob', 'Charlie', 'David', 'Ella', 'Frank', 'Grace', 'Hannah', 'Ian', 'Julia'],
      "Age":[25, 30, 22, 35, 28, 40, 23, 27, 31, 29],
      "Gender":['Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Female']}
df2=pd.DataFrame(data2)
print(df2)

      Name  Age  Gender
0    Alice   25  Female
1      Bob   30    Male
2  Charlie   22    Male
3    David   35    Male
4     Ella   28  Female
5    Frank   40    Male
6    Grace   23  Female
7   Hannah   27  Female
8      Ian   31    Male
9    Julia   29  Female


# Exercise 5: (Score : 1) Add a new column to the data frame created in question 1, called occupation.The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe. 

In [18]:
df2['Occupation'] = ["Programmer", "Manager","Analyst","Manager","Manager","Programmer","Analyst","Programmer","Analyst","Programmer"]
print(df2)

      Name  Age  Gender  Occupation
0    Alice   25  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   22    Male     Analyst
3    David   35    Male     Manager
4     Ella   28  Female     Manager
5    Frank   40    Male  Programmer
6    Grace   23  Female     Analyst
7   Hannah   27  Female  Programmer
8      Ian   31    Male     Analyst
9    Julia   29  Female  Programmer


# Exercise 6: (Score : 1) Select the rows of the dataframe where the age is greater than or equal to 30. 

In [20]:
df2.loc[df2["Age"]>=30]

Name  Age Gender  Occupation
1    Bob   30   Male     Manager
3  David   35   Male     Manager
5  Frank   40   Male  Programmer
8    Ian   31   Male     Analyst

# Exercise 7: (Score : 2) Convert this dataframe to a csv file and read that csv file, finally display the contents.

In [35]:
csv_file="NumpyPandasAss.csv"
df2.to_csv(csv_file,index=False)

In [41]:
df2_as_csv=pd.read_csv("NumpyPandasAss.csv")
print(df2_as_csv)

      Name  Age  Gender  Occupation
0    Alice   25  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   22    Male     Analyst
3    David   35    Male     Manager
4     Ella   28  Female     Manager
5    Frank   40    Male  Programmer
6    Grace   23  Female     Analyst
7   Hannah   27  Female  Programmer
8      Ian   31    Male     Analyst
9    Julia   29  Female  Programmer
